title = "Konstantin Mikheev's programming blog"
baseURL = "http://konmik.com/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
copyright = "(c) Konstantin Mikheev 2020"

[params]
  readMore = "Read"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  fullWidthTheme = false
  centerTheme = true
  # oneHeadingSize = false
  [site]
      copyright = "Copyright"

[menu]
  [[menu.main]]
    identifier = "rss"
    name = "[RSS]"
    url = "http://konmik.com/index.xml"
    weight = 1
  [[menu.main]]
    identifier = "twitter"
    name = "[Twitter]"
    url = "https://twitter.com/sirstripy"
    weight = 2
  [[menu.main]]
    identifier = "github"
    name = "[GitHub]"
    url = "https://github.com/konmik"
    weight = 3
    